CA1/Controllers/ContactsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
//this controller needs to access the Contacts and Sms models 
using CA1.Models;

namespace CA1.Controllers
{
    //this is the 2nd controller (as per assignment specifications) and deals with displaying pre-recorded contact's details
    public class ContactsController : Controller
    {

    // method to return a view that outputs a table (list) of each contact's fname, lname, and phone numbers
    // this method passes a Contacts object (people) to the strongly bound view 'DisplayContacts'
    public ActionResult DisplayContacts()
        {
            //instantiate the Contacts class 
            Contacts contactsTest = new Contacts();
            //so that we can then use the Person list within
            List<Person> people = new List<Person>();
            people = contactsTest.contacts;
            //and pass it to the strongly bound view (bound to an IENumerable of Person)
            return View(people);
        }
    
        // method to receive 2 parameters from the 'DisplayContacts' view
        // this method creates a new Sms object, assigns it the parameters given from View, and passes it to the 'SendSms' view
        public ActionResult ToContact(String destArea, String destNum)
        {
            //instantiate a new Sms obejct
            Sms sms = new Sms();
            //so that we can assign it our two input parameters
            destArea = sms.destArea;
            destNum = sms.destNum;
            //and send it on to the strongly bound 'SendSms' View (bound to the Sms model)
            return View("SendSms", sms);
        }

    }
}

CA1/Controllers/MessageController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using CA1.Models;

namespace CA1.Controllers
{
    // this is the default controller that handles message sending 
    public class MessageController : Controller
    {
        //[GET}
        // this is the default ActionResult --> returns a View for sending a new message
        public ActionResult SendSms()
        {
            return View();
        }

        //this ActionResult receives an Sms 'object' back from the form in the 'SendSms' View
        [HttpPost]
        public ActionResult SendSms(Sms sms)
        {
            //this is back end validation ( the front end validation can be found within View) --> both are bound to the model 
            //handles event where any model errors have been added to ModelState (eg a bool instead of string)
            if (ModelState.IsValid)
            {
                // instantiate a new Contacts object to search the List within
                Contacts testContacts = new Contacts();
                // and assign output to a string 
                string search = testContacts.search(sms.destArea, sms.destNum);

                //then incase a match was found, we need to pass the fName and lNames on to the View to be returned  
                // as this is a RedirectToAction we need to use a TempData
                TempData["searchoutput"] = search;
                
                //we also need to pass on the SmsText input param to the View to be returned 
                // as this is a RedirectToAction we need to use a TempData
                TempData["message"] = sms.smsText;
                
                //when the search() method finds no match within the contacts list
                if (search == "nomatch")
                    return RedirectToAction("Error");
                //search() found a match --> we then return a Succes view with a confirmation message.
                else
                {
                    // this method logs all messages sent to the Output Debug console in VS
                    CA1.SentMessageLog.outputToDebugConsole(sms.smsText);
                    return RedirectToAction("Succes");             
                }
            }
            //if the Modelstate is not valid --> this ActionResult will pass its fields (including non-valid ones) back to the view. User can then modify.
            return View(sms);
        }


        public ActionResult Succes()
        {
            ViewBag.Message = TempData["searchoutput"].ToString();
            ViewBag.SmsMessage = TempData["message"].ToString();

            return View();
        }


        public ActionResult Error()
        {
            ViewBag.Message = TempData["searchoutput"].ToString();
            ViewBag.SmsMessage = TempData["message"].ToString();

            return View();
        }

    }
}

CA1/Views/Shared/SendSms.cshtml
@model CA1.Models.Sms

@{
    ViewBag.Title = "Send an SMS";
}

<h2>Send an SMS</h2>
<!--tells the form where to send the user inputs and the HTML attributes
    I could not use Html.BeginForm(action, method) as this caused the form to post back
    to the wrong controller (in cases where model passed from the Contacts controller)-->
<form action="/Message/SendSms" method="post">
    <!--used to You can specify error messages against the model
        The bool property indicates we would like to display the validation summary error messages 
        at the same time as displaying the property error messages-->
    @Html.ValidationSummary(true)
    <fieldset>
        <!--styling for the textbox-->
        <div class="editor-label">
            <!--this looks in the model to find the label for the 'smsText' property-->
            @Html.LabelFor(model => model.smsText)
        </div>
        <div class="editor-field">
            <!--here we use the larger TextAreaFor textbox (for user input) as the SMS is can be up to 140characters-->
            @Html.TextAreaFor(model => model.smsText)
            <!--this is the client-side validation bound to the model-->
            @Html.ValidationMessageFor(model => model.smsText)
        </div>


        <div class="editor-label">
            @Html.LabelFor(model => model.destArea)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.destArea)
            @Html.ValidationMessageFor(model => model.destArea)
        </div>


        <div class="editor-label">
            @Html.LabelFor(model => model.destNum)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.destNum)
            @Html.ValidationMessageFor(model => model.destNum)
        </div>
        <p>
            <!--this button goes to send off the form-->
            <input type="submit" value="Send Message" />
        </p>
    </fieldset>
</form>

<!--this is important as it renders the jquery files necessary for client side (front end) validation-->
@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

CA1/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <title>@ViewBag.Title - Yan's ASP.NET MVC SMS Application</title>
        <link href="~/favicon.ico" rel="shortcut icon" type="image/x-icon" />
        <meta name="viewport" content="width=device-width" />
        @Styles.Render("~/Content/css")
        @Scripts.Render("~/bundles/modernizr")
    </head>
    <body>
        <header>
            <div class="content-wrapper">
                <div class="float-left">
                    <p class="site-title">@Html.ActionLink("Enterprise App. Design (CA1)", "SendSms", "Message")</p>
                </div>
                <div class="float-right">
                    <nav>
                        <ul id="menu">
                            <li>@Html.ActionLink("Send an Sms", "SendSms", "Message")</li>
                            <li>@Html.ActionLink("View Contacts", "DisplayContacts", "Contacts")</li>
                            <li>@Html.ActionLink("About Yan's CA1", "About", "Home")</li>
                        </ul>
                    </nav>
                </div>
            </div>
        </header>
        <div id="body">
            @RenderSection("featured", required: false)
            <section class="content-wrapper main-content clear-fix">
                @RenderBody()
            </section>
        </div>
        <footer>
            <div class="content-wrapper">
                <div class="float-left">
                    <p>Made in @DateTime.Now.Year | Yan's ASP.NET MVC Application</p>
                </div>
            </div>
        </footer>

        @Scripts.Render("~/bundles/jquery")
        @RenderSection("scripts", required: false)
    </body>
</html>